export default {
  logo: require("../assets/images/logo.png.webp"),
  bg_about: require("../assets/images/about.jpg.png"),
  about: require("../assets/images/about_story.webp"),
  bg_contact: require("../assets/images/contact_top.webp"),
  bg_blogs: require("../assets/images/blog_top.webp"),
  blogs1: require("../assets/images//blog-01.jpg"),
  blogs2: require("../assets/images//blog-02.jpg"),
  blogs3: require("../assets/images//blog-03.jpg"),
  product1: require("../assets/images/product1.webp"),
  product2: require("../assets/images/product2.webp"),
  product3: require("../assets/images/product3.webp"),
  product4: require("../assets/images/product4.webp"),
  product5: require("../assets/images/product5.webp"),
  product6: require("../assets/images/product6.webp"),
  product7: require("../assets/images/product7.webp"),
  product8: require("../assets/images/product8.webp"),
};
